---
# handlers file for httpd
- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: restart httpd
  service: 
    name: httpd
    state: restarted

- name: reload firewalld
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld

